name: Concurrency

on: [push] 
concurrency:
  # This workflow should be triggered for any branch only once
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # existing will be cancelled and latest will run
jobs: 
  concurrency: 
    runs-on: ubuntu-latest 
    steps: 
      - name: step1
        run: sleep 20